FROM hashicorp/vault:latest

USER root

# Créer le répertoire et configurer les permissions
RUN mkdir -p /vault/data && \
    chown -R vault:vault /vault && \
    chmod -R 755 /vault

USER vault

ENTRYPOINT ["vault"]